### ISSUE TITLE
Load all variables from database/folder in Coldbir format

### ISSUE THREAD

**Issue by captHaddock** [SwedishPensionsAgency/Coldbir#11]
Hi,

I would like to have the possibility to load all variables from a database/folder at once with Coldbir. Right now I have to pick variable by variable one at the time.

/ Marcus

**Comment by reinholdsson** [comment]
:+1:

**Comment by reinholdsson** [comment]
Here is an example of a solution, given all variables has the same length and without support of `dims`:

```
require(data.table)

# Example DB
a <- cdb(tempfile(), type = "f")
a["char"] <- c("foo", "bar", "foo")
a["int"] <- 1:3
a["na"] <- c(3, NA, NA)

# Get all variables
vars <- get_vars(a, dims = FALSE)

# Read all variables to a list
x <- lapply(vars, function(x){
    dt <- data.table(a[x])
    setnames(dt, names(dt), x)
    return(dt)
})

# Combine as one data table
dt <- do.call("cbind", x)
```

#### Fill NA

Perhaps it is possible to use something like `cbind.fill` or `merge(..., by = "row.names")`?

#### Dims

This could for example be achieved by using `a[ , c(2011, 12)]` as syntax. However, it would only make it possible to select one dimension at once.

**Comment by reinholdsson** [comment]
TODO:
- [ ] Vectorize get_variable; add support get variables as a `data.table`, e.g. `a[c("var1", "var2")]`. Dimensions would then apply to all variables provided.

**Comment by reinholdsson** [comment]
Another example:

```
get_all <- function(cdb, dim, vars = get_vars(cdb)) {
  x <- data.table(x = cdb[vars[1], dim])
  setnames(x, "x", vars[1])

  for(i in vars[2:length(vars)]){
    x[ , i := cdb[i, dim], with = F]
  }

  return(x)
}

ped <- get_all(cdb = a, dim = .DIM)
pab <- get_all(cdb = b, dim = .DIM)
```
