### ISSUE TITLE
Database config file

### ISSUE THREAD

**Issue by reinholdsson** [SwedishPensionsAgency/Coldbir#39]
Add database config file, that let the user set defaults used in the `cdb` function. The file is saved as `config.json` in the database directory.

Syntax to set the config file:

```
a$config(...)
```

**Comment by mikula** [comment]
I assume that we switch to RJSONIO for implemenation.

**Comment by reinholdsson** [comment]
That's right! I have now updated it to `config.json`.

**Comment by mikula** [comment]
... or  general R-serialization.
saveRDS(XX,file=path)
YY<-readRDS(file=path)
seems to be much more efficient.
We don't need this information readable by humans in the file system. It's sufficient with possibilityof fetching it from R
thus config.dat?...
