### ISSUE TITLE
New query syntax for (multiple) variables

### ISSUE THREAD

**Issue by reinholdsson** [SwedishPensionsAgency/Coldbir#55]
**UPDATE**: See comments by @mikula in this discussion.

E.g. some variables have dimensions by year, while as for example ID-variables are the same for each year (`dim = NULL`). It could be nice if they were also included when loading a table from Coldbir, e.g:

```
dt <- a[, c(2012, 12)]
```

**Comment by mikula** [comment]
I will look into this. The complexity of this problem is slightly bigger

**Comment by mikula** [comment]
We can reduce the possibilities to a few cases:

a[] -> the total database
a[, c(2005,12)] -> all variables with this dimension
a[, c(.ANY, 12)] -> all variables with data with matching dimensions (def .ANY <- NA)
a[, c(.ANY, .ANY)] -> all vectorr for all variables with dimensionality of two
a[c("V1","V2", ... , "Vn"),(2005,12)]  -> all named variables with this dimension
a[c("V1","V2", ... , "Vn"),(.ANY,12)]  ... etc

**Comment by mikula** [comment]
An observation:
If we are content with the wildcards, the system can allow multiple dimensionality of variables.
e.g. I38 could is lost in both the dime tion year and year-month
["I38", c (2010, 12)] - means payments of inkomstpension for December month
["I38", c (2010)] - would then mean payments for the year 2010
even more ... ["I38"] could mean so far all payments made or an indication of the presence of any value of the individual (most for selections)

**Comment by mikula** [comment]
implemantation in branch: issue55

**Comment by mikula** [comment]
Before the pull request
 I will fix the symentry of following opertions:
x <- db1[]
db2[] <- x # should create an exact copy of db1 in the path for db2

**Comment by reinholdsson** [comment]
See the following link for current API examples:
https://gist.github.com/reinholdsson/8678370

Should we change something?

**Comment by reinholdsson** [comment]
This should all be implemented by now, however, see related issue #98.
