### ISSUE TITLE
Use jsonlite instead of RJSONIO?

### ISSUE THREAD

**Issue by reinholdsson** [SwedishPensionsAgency/Coldbir#62]
Under active development, but could be interesting if we have problems with encoding: https://github.com/jeroenooms/jsonlite

**Comment by mikula** [comment]
At least for storing and reading data we should remain with the faster RJSONIO. In many of my scripts I need read new vectors ferquently. When it comes to the documantation the speed isn't so crucial and problems with encoding are possibly bigger (Are they?...). So if there is any advatages of switching to jsonlite we should use both.

**Comment by reinholdsson** [comment]
Currently `RJSONIO` works quite well so we will close this issue at the moment, otherwise we will re-open it later on.
