### ISSUE TITLE
Possible changes to `[<-`?

### ISSUE THREAD

**Issue by reinholdsson** [SwedishPensionsAgency/Coldbir#84]
When adding a `data.frame`/`data.table` to the database, we're using `.` in the column names to automatically define name/dims for variables, and this causes a bit of confusion. E.g.

```
library(Coldbir)
a <- cdb(tempfile())
a[] <- MASS::survey

a[, c(2012)] <- MASS::survey
# Warning messages:
#   1: In wrn(25, name) :
#   Wr.Hnd wasn't added since '.' aren't supported as variable names.
# ...

a[, ._]
# Returns:
# Age.2012, Clap.2012, Exer.2012, Fold.2012, 
# Height.2012, M.I, NW.Hnd, Pulse.2012,
# Sex.2012, Smoke.2012, W.Hnd, Wr.Hnd
```

Solutions?
- [**Implemented**] Use another delimiter (e.g. `..`), if so, we also need to find an alternative to `unlist` (see #80).
- Remove this feature, **but** then the following wouldn't be possible `b[] <- a[]`.
- Add attributes describing the dimensions to the returned table. The attributes could be a list similar to `a$variables`, or a list with all columns (variables) where each child (`x`) is a character vector: `x[1] => name, x[-1] => dimensions`. Either we simply add the attributes to the table or we define a subclass of `data.table`. But, what if the user changes the table?
- Add an argument if this should apply, e.g. `b[colsplit = T] <- a[]`.

@mikula any suggestions? :)

**Comment by mikula** [comment]
We should allow an arbitary delimiter. Default value could be "___"  (3x"_")
Each databasetable could change it.

"unlist" could  replaced with 

cbd_unlist <- function(L , nStr ="", del = "___")
{
  if(!is.list(L))
  {
    x <- 1;names(x) <- nStr
    return(x)
  }

  res <- integer(0) 
  actNstr <- names(L)

  for(i in 1:length(L)) 
  {
    if(nStr!="" ) actNstr[i] <- ifelse(actNstr[i]==".",nStr, paste(nStr,actNstr[i], sep = del) ) 
    res <- c(res, cbd_unlist(L= L[[i]], nStr = actNstr[i]))

  }

  return(res)
}
example:
L <-list("a.a" = list("b" = list(. = 1), "c" = list(. = 1)),
         "x"   = list("b" = list("z" = list(.=1)), "c" = list(. = 1)))
cbd_unlist(L)

  a.a___b   a.a___c x___b___z     x___c 
        1         1         1         1

**Comment by reinholdsson** [comment]
Excellent! The first alternative has now been implemented. "___" is currently chosen as the delimiter (it is set as a constant within the package, see `.cdb_sep`. Later on, we could add it to the config file.
